#!/usr/bin/env bash
#
DT=$(date +%Y-%m-%d_%H%M)
DEST=.

UN=username
PWD=password
DB=database
DBHOST=databasehost
#
if [ -d $DEST ];  then
 echo "****************************************"
 echo " BOOKS BACKUP STARTING..."
 echo
 BOOKSDBDUMP=booksdb_$DT.sql
 mysqldump -h$DBHOST -u$UN -p$PWD $DB "book collection" "tags" > $DEST/$BOOKSDBDUMP
 /cygdrive/c/Program\ Files\ \(x86\)/MySQL/MySQL\ Workbench\ 5.2\ CE/mysqldump.exe -h$DBHOST -u$UN -p$PWD $DB "book collection" "tags" > $DEST/$BOOKSDBDUMP
 echo "Backups present:"
 ls -lhs ./booksdb*
 echo "Done."
 echo "****************************************"
else
 echo "Destination $DEST does not exist. Aborting."
fi

